# Checks that the project can build

name: build

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        java: [
          8 # Classic runs on Java 8
        ]
        os: [ ubuntu-20.04, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-jdk${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/gradle-wrapper.properties', '.github/workflows/build.yml') }}
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Gradle Clean
        run: ./gradlew clean
      - name: Gradle Check
        run: ./gradlew check
      - name: Gradle Build
        run: ./gradlew build
      - name: Capture Build Artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '8' }}
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
